// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using DigitalSocieties.Identity.Infrastructure.Persistence;

[assembly: DbContext(typeof(IdentityDbContext))]

namespace DigitalSocieties.Identity.Infrastructure.Persistence.Migrations;

[DbContext(typeof(IdentityDbContext))]
partial class IdentityDbContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
        modelBuilder.HasDefaultSchema("identity")
                    .HasAnnotation("ProductVersion", "8.0.4")
                    .HasAnnotation("Relational:MaxIdentifierLength", 63);
        // Full snapshot generated by EF tooling on first `dotnet ef migrations add`
        // Run: dotnet ef migrations add InitialCreate --project DigitalSocieties.Identity
        //       --startup-project DigitalSocieties.Api
    }
}
