// <auto-generated />
using System;
using DigitalSocieties.Accounting.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DigitalSocieties.Accounting.Infrastructure.Persistence.Migrations;

[DbContext(typeof(AccountingDbContext))]
partial class AccountingDbContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "8.0.4")
            .HasAnnotation("Relational:MaxIdentifierLength", 63);

        NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

        modelBuilder.Entity("DigitalSocieties.Accounting.Domain.Entities.LedgerEntry", b =>
        {
            b.Property<Guid>("Id")
                .HasColumnType("uuid")
                .HasColumnName("id")
                .HasDefaultValueSql("gen_random_uuid()");

            b.Property<long>("AmountPaise")
                .HasColumnType("bigint")
                .HasColumnName("amount_paise");

            b.Property<DateTimeOffset?>("ApprovedAt")
                .HasColumnType("timestamp with time zone")
                .HasColumnName("approved_at");

            b.Property<Guid?>("ApprovedBy")
                .HasColumnType("uuid")
                .HasColumnName("approved_by");

            b.Property<string>("Category")
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnType("character varying(100)")
                .HasColumnName("category");

            b.Property<DateTimeOffset>("CreatedAt")
                .HasColumnType("timestamp with time zone")
                .HasColumnName("created_at")
                .HasDefaultValueSql("NOW()");

            b.Property<Guid?>("CreatedBy")
                .HasColumnType("uuid")
                .HasColumnName("created_by");

            b.Property<string>("Description")
                .IsRequired()
                .HasMaxLength(500)
                .HasColumnType("character varying(500)")
                .HasColumnName("description");

            b.Property<DateOnly>("EntryDate")
                .HasColumnType("date")
                .HasColumnName("entry_date");

            b.Property<bool>("IsDeleted")
                .HasDefaultValue(false)
                .HasColumnType("boolean")
                .HasColumnName("is_deleted");

            b.Property<Guid>("PostedBy")
                .HasColumnType("uuid")
                .HasColumnName("posted_by");

            b.Property<string>("RejectionReason")
                .HasMaxLength(500)
                .HasColumnType("character varying(500)")
                .HasColumnName("rejection_reason");

            b.Property<string>("ReceiptUrl")
                .HasMaxLength(500)
                .HasColumnType("character varying(500)")
                .HasColumnName("receipt_url");

            b.Property<Guid>("SocietyId")
                .HasColumnType("uuid")
                .HasColumnName("society_id");

            b.Property<string>("Status")
                .IsRequired()
                .HasMaxLength(30)
                .HasDefaultValue("Approved")
                .HasColumnType("character varying(30)")
                .HasColumnName("status");

            b.Property<string>("Type")
                .IsRequired()
                .HasMaxLength(20)
                .HasColumnType("character varying(20)")
                .HasColumnName("type");

            b.Property<DateTimeOffset>("UpdatedAt")
                .HasColumnType("timestamp with time zone")
                .HasColumnName("updated_at")
                .HasDefaultValueSql("NOW()");

            b.Property<Guid?>("UpdatedBy")
                .HasColumnType("uuid")
                .HasColumnName("updated_by");

            b.HasKey("Id").HasName("pk_ledger_entries");

            b.HasIndex("SocietyId").HasDatabaseName("ix_ledger_entries_society_id");
            b.HasIndex("EntryDate").HasDatabaseName("ix_ledger_entries_entry_date");

            b.ToTable("ledger_entries", "accounting");
        });
#pragma warning restore 612, 618
    }
}
