// <auto-generated />
using System;
using DigitalSocieties.Facility.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DigitalSocieties.Facility.Infrastructure.Persistence.Migrations;

[DbContext(typeof(FacilityDbContext))]
partial class FacilityDbContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "8.0.4")
            .HasAnnotation("Relational:MaxIdentifierLength", 63);

        NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

        modelBuilder.Entity("DigitalSocieties.Facility.Domain.Entities.Facility", b =>
        {
            b.Property<Guid>("Id").HasColumnType("uuid").HasColumnName("id").HasDefaultValueSql("gen_random_uuid()");
            b.Property<Guid>("SocietyId").HasColumnType("uuid").HasColumnName("society_id");
            b.Property<string>("Name").IsRequired().HasMaxLength(150).HasColumnName("name");
            b.Property<string>("Description").IsRequired().HasMaxLength(500).HasColumnName("description");
            b.Property<string>("ImageUrl").HasMaxLength(500).HasColumnName("image_url");
            b.Property<int>("CapacityPersons").HasColumnType("integer").HasColumnName("capacity_persons");
            b.Property<int>("SlotDurationMinutes").HasDefaultValue(60).HasColumnName("slot_duration_minutes");
            b.Property<TimeOnly>("OpenTime").HasColumnType("time without time zone").HasColumnName("open_time");
            b.Property<TimeOnly>("CloseTime").HasColumnType("time without time zone").HasColumnName("close_time");
            b.Property<bool>("IsActive").HasDefaultValue(true).HasColumnName("is_active");
            b.Property<int>("AdvanceBookingDays").HasDefaultValue(7).HasColumnName("advance_booking_days");
            b.Property<int>("MaxBookingsPerFlat").HasDefaultValue(2).HasColumnName("max_bookings_per_flat");
            b.Property<bool>("IsDeleted").HasDefaultValue(false).HasColumnName("is_deleted");
            b.Property<DateTimeOffset>("CreatedAt").HasDefaultValueSql("NOW()").HasColumnName("created_at");
            b.Property<Guid?>("CreatedBy").HasColumnName("created_by");
            b.Property<DateTimeOffset>("UpdatedAt").HasDefaultValueSql("NOW()").HasColumnName("updated_at");
            b.Property<Guid?>("UpdatedBy").HasColumnName("updated_by");
            b.HasKey("Id").HasName("pk_facilities");
            b.HasIndex("SocietyId").HasDatabaseName("ix_facilities_society_id");
            b.ToTable("facilities", "facility");
        });

        modelBuilder.Entity("DigitalSocieties.Facility.Domain.Entities.FacilityBooking", b =>
        {
            b.Property<Guid>("Id").HasColumnType("uuid").HasColumnName("id").HasDefaultValueSql("gen_random_uuid()");
            b.Property<Guid>("FacilityId").HasColumnType("uuid").HasColumnName("facility_id");
            b.Property<Guid>("SocietyId").HasColumnType("uuid").HasColumnName("society_id");
            b.Property<Guid>("BookedBy").HasColumnType("uuid").HasColumnName("booked_by");
            b.Property<Guid>("FlatId").HasColumnType("uuid").HasColumnName("flat_id");
            b.Property<DateOnly>("BookingDate").HasColumnType("date").HasColumnName("booking_date");
            b.Property<TimeOnly>("StartTime").HasColumnType("time without time zone").HasColumnName("start_time");
            b.Property<TimeOnly>("EndTime").HasColumnType("time without time zone").HasColumnName("end_time");
            b.Property<string>("Status").IsRequired().HasMaxLength(20).HasDefaultValue("Confirmed").HasColumnName("status");
            b.Property<string>("Notes").HasMaxLength(500).HasColumnName("notes");
            b.Property<DateTimeOffset?>("CancelledAt").HasColumnName("cancelled_at");
            b.Property<Guid?>("CancelledBy").HasColumnName("cancelled_by");
            b.Property<bool>("IsDeleted").HasDefaultValue(false).HasColumnName("is_deleted");
            b.Property<DateTimeOffset>("CreatedAt").HasDefaultValueSql("NOW()").HasColumnName("created_at");
            b.Property<Guid?>("CreatedBy").HasColumnName("created_by");
            b.Property<DateTimeOffset>("UpdatedAt").HasDefaultValueSql("NOW()").HasColumnName("updated_at");
            b.Property<Guid?>("UpdatedBy").HasColumnName("updated_by");
            b.HasKey("Id").HasName("pk_facility_bookings");
            b.HasIndex("FacilityId").HasDatabaseName("ix_facility_bookings_facility_id");
            b.HasIndex("BookedBy").HasDatabaseName("ix_facility_bookings_booked_by");
            b.ToTable("facility_bookings", "facility");

            b.HasOne("DigitalSocieties.Facility.Domain.Entities.Facility", "Facility")
                .WithMany("Bookings")
                .HasForeignKey("FacilityId")
                .HasConstraintName("fk_facility_bookings_facilities")
                .OnDelete(DeleteBehavior.Restrict)
                .IsRequired();
        });
#pragma warning restore 612, 618
    }
}
