import { appSchema, tableSchema } from '@nozbe/watermelondb';

/** SQLite schema — version-controlled; migrations below. */
export const schema = appSchema({
  version: 1,
  tables: [
    tableSchema({ name: 'users', columns: [
      { name: 'server_id',    type: 'string', isIndexed: true },
      { name: 'phone',        type: 'string', isIndexed: true },
      { name: 'name',         type: 'string' },
      { name: 'email',        type: 'string', isOptional: true },
      { name: 'avatar_url',   type: 'string', isOptional: true },
      { name: 'is_active',    type: 'boolean' },
      { name: 'last_login_at', type: 'number', isOptional: true },
    ]}),
    tableSchema({ name: 'societies', columns: [
      { name: 'server_id',   type: 'string', isIndexed: true },
      { name: 'name',        type: 'string' },
      { name: 'address',     type: 'string' },
      { name: 'tier',        type: 'string' },
      { name: 'logo_url',    type: 'string', isOptional: true },
      { name: 'total_flats', type: 'number' },
    ]}),
    tableSchema({ name: 'memberships', columns: [
      { name: 'server_id',   type: 'string', isIndexed: true },
      { name: 'user_id',     type: 'string', isIndexed: true },
      { name: 'society_id',  type: 'string', isIndexed: true },
      { name: 'flat_id',     type: 'string', isOptional: true },
      { name: 'role',        type: 'string' },
      { name: 'member_type', type: 'string' },
      { name: 'is_active',   type: 'boolean' },
    ]}),
    tableSchema({ name: 'bills', columns: [
      { name: 'server_id',    type: 'string', isIndexed: true },
      { name: 'flat_id',      type: 'string', isIndexed: true },
      { name: 'society_id',   type: 'string', isIndexed: true },
      { name: 'amount_paise', type: 'number' },
      { name: 'period',       type: 'string' },
      { name: 'status',       type: 'string', isIndexed: true },
      { name: 'description',  type: 'string' },
      { name: 'due_date',     type: 'number' },
      { name: 'paid_at',      type: 'number', isOptional: true },
    ]}),
    tableSchema({ name: 'visitors', columns: [
      { name: 'server_id',      type: 'string', isOptional: true },
      { name: 'name',           type: 'string' },
      { name: 'phone',          type: 'string' },
      { name: 'flat_number',    type: 'string' },
      { name: 'purpose',        type: 'string' },
      { name: 'status',         type: 'string', isIndexed: true },
      { name: 'vehicle_number', type: 'string', isOptional: true },
      { name: 'photo_url',      type: 'string', isOptional: true },
      { name: 'is_synced',      type: 'boolean' },
      { name: 'entry_time',     type: 'number' },
      { name: 'exit_time',      type: 'number', isOptional: true },
      { name: 'approved_at',    type: 'number', isOptional: true },
    ]}),
    tableSchema({ name: 'complaints', columns: [
      { name: 'server_id',   type: 'string', isOptional: true },
      { name: 'title',       type: 'string' },
      { name: 'description', type: 'string' },
      { name: 'category',    type: 'string' },
      { name: 'status',      type: 'string', isIndexed: true },
      { name: 'priority',    type: 'string' },
      { name: 'flat_id',     type: 'string' },
      { name: 'is_synced',   type: 'boolean' },
      { name: 'created_at',  type: 'number' },
      { name: 'resolved_at', type: 'number', isOptional: true },
    ]}),
    tableSchema({ name: 'notices', columns: [
      { name: 'server_id', type: 'string', isIndexed: true },
      { name: 'title',     type: 'string' },
      { name: 'body',      type: 'string' },
      { name: 'type',      type: 'string' },
      { name: 'is_read',   type: 'boolean' },
      { name: 'posted_at', type: 'number' },
      { name: 'expires_at', type: 'number', isOptional: true },
    ]}),
  ]
});
